name: 'kafka'
version: 0.1.0
description: Kafka client library for Dartlang
homepage: https://github.com/dart-drivers/kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.10.0
  quiver: ^3.2.1
  logging: ^1.1.1
  pool: ^1.5.1
  collection: ^1.17.1

dev_dependencies:
  test: ^1.22.2
  mockito: ^5.3.2
#  dart_coveralls: ^0.6.0+4
  string_scanner: ^1.2.0
  source_span: ^1.9.1
